#
# Copyright (C) 2017  Artur B.
#

FROM node:7

RUN apt-get update && apt-get -y install nano
RUN mkdir -p /usr/src/app

# Copy & install app dependencies
COPY . /usr/src/app
WORKDIR /usr/src/app
RUN npm install # && npm rebuild node-sass --force

EXPOSE 4200
CMD ["npm", "start"]
